### ISSUE TITLE
Daftar Bug

### ISSUE THREAD

**Issue by ardinusawan** [ardinusawan/Pemrograman_Jaringan_C#2]
Tugas_3
1. Untuk menggunakan laser, tekan CTRL. Jika posisi x pada laser = x pada musuh || posisi y pada laser = y pada musuh, timbul suatu keanehan. Coba saja sendiri
2. Jika musuh terkena laser, harusnya hanya dia yg dc. Tapi ini malah semua player -_-
3. Yang dipakai GUIClient2 ya, soalnya GUIClient corrupt filenya.

Jawaban dari to do Dhanar : 
1. Class Peluru ->ga perlu sepertinya, soalnya kalo dibuat class, fungsi JPanelnya aku bingung -_-,
 fungsi nembak ->udah, make keyboard ctrl, 
 dan kondisi mati kalo ketembak->ini yg masih nge-bug
2. Ganti gambar orang yang ukurannya kotak (panjang==lebar) (WAJIB) -> tolong dong yang lain :v: 
3. fix bug: kalo ada client yang keluar game tanpa “disconnect”, server
bakal error(terutama serverstop) -> blum diperbaiki

**Comment by dhiazfathra** [comment]
Ganti gambar kayaknya gk perlu, udah terlanjur banyak.
